@revisao_HostAddress = http://localhost:5102
@id = 1
GET {{revisao_HostAddress}}/
Accept: application/json

###

POST {{revisao_HostAddress}}/add_user/
Accept: application/json
Content-Type: application/json

{
    "name":"loki",
    "Age":1420
}

###
GET {{revisao_HostAddress}}/get_user/{{id}}

###

GET {{revisao_HostAddress}}/get_users

###

PUT {{revisao_HostAddress}}/update_user/{{id}}
Accept: application/json
Content-Type: application/json

{
    "name":"Lorem Ipsum",
    "Age":10
}


###

DELETE {{revisao_HostAddress}}/delete_user/{{id}}
